version: '2'
services:
     mrtrgw:
         build : . 
         image : mrtrgw:0.0.1
         restart: always
         volumes:
              - ./logs:/var/log/nginx
         ports:
              - 7000:7000
         environment:
              - SET_CONTAINER_TIMEZONE=true
              - CONTAINER_TIMEZONE=Asia/Bangkok
              - TZ=ICT-7
